[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
    "setuptools_scm>=3.3.1",
    "tox"
]

[tool.black]
line-length = 200
target-version = ['py39']
skip-string-normalization = true
ignore = ".venv"
